### ISSUE TITLE
Host key verification failed (new cli?)

### ISSUE THREAD

**Issue by oscarlofwenhamn** [appleboy/drone-git-push#37]
New issue since the solutions in #16 and #28 seem to be using an old cli, since the `--image` tag is not present in the current drone cli, and trying to port their solutions haven't worked.

I am running Drone on a remote server, and am using it to create a sort of gated check-in to my Gitea repo. This involves manually pushing to branch A, after which tests are run and if the tests are completed the code is merged and pushed to branch B. I want to make this push using SSH keys related to a service account.
Despite verifying that the SSH key pair is functional, and being able to do the same push using HTTPS instead, I keep getting the following error when using this plugin:
```sh
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit status 128
```

This is my yaml definition for the step:
```yaml
  - name: push
    depends_on:
    - merge
    image: appleboy/drone-git-push
    settings:
      branch: B
      remote: git@gitea-host:owner/repo.git
```
and I've set the secret `GIT_PUSH_SSH_KEY`, and signed the yaml as follows:
```sh
drone secret add --name GIT_PUSH_SSH_KEY --data @relative/path/to/id_rsa user/repo
drone sign user/repo --save
```

Am I missing something obvious, or does someone have a suggestion as to what I am doing wrong?

**Comment by Mali-Coxon** [comment]
I have the same situation, but I've tried a multitude of combinations (including adding it twice in my config) to try and get this key working. I'm trying to use the secrets in the visual interface which I imagine (I might be wrong) is the same as the CLI at its core?

```
  - name: deploy
    image: appleboy/drone-git-push
    environment:
      key:
        from_secret: ssh_key
    settings:
      branch: master
      remote: 
      force: false
      commit: true
      key:
        from_secret: ssh_key
```

I wonder if it's a symptom of a bigger problem?

**Comment by oscarlofwenhamn** [comment]
> I had to add this:

Yes, I was just about to reply with this too - though I used `PLUGIN_SSH_KEY:` which seems to work as well. Good to hear you figured it out as well! Hopefully someone who comfortably knows this to be the most correct solution can reply and/or open a PR to fix the docs, it was a frustrating problem to run into. If it can be confirmed as the correct solution I can sort a PR out too, but I want it confirmed.

**Comment by naorlivne** [comment]
https://github.com/appleboy/drone-git-push/blob/ea1c690bdec5e37b2a7777b590d4e6e1320023cd/main.go#L53 seems to indicate that the docs should be changed from `key` to `ssh_key` so it should look something like:

```yaml
    settings:
      ssh_key:
        from_secret: ssh_key
```
