### ISSUE TITLE
Bug: Remote URL's Formatting Error

### ISSUE THREAD

**Issue by Blackglade** [appleboy/drone-git-push#40]
## Description

I had several builds fail this morning as they tried to push GitHub code to a repo via a drone pipeline. The error occurred in the final step of my pipeline:

```
  - name: Publish website
    image: appleboy/drone-git-push
    settings:
      remote_name: test_repo
      remote: git@custom_url.com:test/test.git
      branch: gh-pages
      path: /drone/src/website
      key: GIT_PUSH_SSH_KEY
      force: true
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: GIT_PUSH_SSH_KEY
```

The error was as follows:

```
time="2020-03-09T18:33:42Z" level=fatal msg="parse \"git@custom_url.com:test/test.git\": first path segment in URL cannot contain colon"
```

This is likely occurring because a regression of a previous issue with `net/url` in 1.14. See this issue: https://github.com/golang/go/issues/29261

Changing the image from `appleboy/drone-git-push` to `appleboy/drone-git-push:0.2.0-linux-alpine` to migrate to the last working version resolved the issue.
