### ISSUE TITLE
error: colon in url path

### ISSUE THREAD

**Issue by volker-raschek** [appleboy/drone-git-push#44]
Hey, I get the following error when I want to push the code on github.

```bash
time="2020-06-14T12:33:21Z" level=fatal msg="parse \"git@github.com:fh-trier/latex-templates.git\": first path segment in URL cannot contain colon"
```
https://drone.cryptic.systems/fh-trier/latex-templates/8/1/3

Here is my defined drone.yml section:

```yaml
- name: push-latest-commit
  image: appleboy/drone-git-push
  settings:
    remote: git@github.com:fh-trier/latex-templates.git
    force: true
    key:
      from_secret: github_ssh_key
  when:
    repo:
    - fh-trier/latex-templates
    branch:
    - master
    event:
    - push
```

Can someone explain to me where the error is? I think I have set it up as described in the [documentation](http://plugins.drone.io/appleboy/drone-git-push/) or is it out of date?

Volker

**Comment by bregydoc** [comment]
I have the same issue.

**Comment by proapi** [comment]
I have the same issue, did you find a solution?

**Comment by volker-raschek** [comment]
@proapi, no I did not find any solution at the moment.

**Comment by yvvas** [comment]
This is actually a bug with some go pkg so use this image instead...
`image: appleboy/drone-git-push:0.2.0-linux-amd64`

**Comment by appleboy** [comment]
replace

```sh
git@github.com:fh-trier/latex-templates.git
```

with

```sh
ssh://git@github.com/fh-trier/latex-templates.git
```

**Comment by laur89** [comment]
I've two repositories with identical steps:
```yml
- name: git-push
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: github_ssh_key
    remote: "${DRONE_GIT_SSH_URL}"
  when:
    branch:
    - master
```

One of them pushes successfully, other complains about the colon-in-url. What gives? `DRONE_GIT_SSH_URL` should refer to the remote syntax you suggested in either case.
