### ISSUE TITLE
Help wanted with dokku remote

### ISSUE THREAD

**Issue by HectorCastelli** [appleboy/drone-git-push#45]
When trying to push to a Dokku remote, I get errors.

For the following examples  `website` is my application name and `domain.com` is the domain that points to my server.

## Running locally

On a local machine, this is as simple as running:

1. `ssh-add dokku_key`
2. `git remote add dokku dokku@domain.com:website`
3. `git push dokku`

## First attempt

With the following drone config
```
  - name: push commit
    image: appleboy/drone-git-push
    settings:
      ssh_key:
        from_secret: dokku_ssh_key
      remote: dokku@domain.com:website
      remote_name: dokku
```
I get the error:
```
level=fatal msg="parse \"dokku@domain.com:website\": first path segment in URL cannot contain colon"
```

I imagine this is because of the lack of a protocol, in this case ssh. After adding it and trying again, no luck...

## Second attempt
```
  - name: push commit
    image: appleboy/drone-git-push
    settings:
      ssh_key:
        from_secret: dokku_ssh_key
      remote: ssh://dokku@domain.com:website
      remote_name: dokku
```
I get the error:
```
level=fatal msg="parse \"ssh://dokku@domain.com:website\": invalid port \":website\" after host"
```
