### ISSUE TITLE
fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled

### ISSUE THREAD

**Issue by sevaho** [appleboy/drone-git-push#55]
Follow up of https://github.com/appleboy/drone-git-push/issues/49 with

Hi

I am using the latest release v0.2.2

Since a couple of weeks I have a problem with pushing content from drone to git with the following error:

```
+ git add --all
+ git diff-index --quiet HEAD --ignore-submodules
+ git push origin HEAD:master
fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled
exit status 128
```

I am using the plugin as follows:

```
kind: pipeline
name: debug ci

steps:
  - ...
  - name: Push changes to master
    image: appleboy/drone-git-push:0.2.2
    settings:
      remote_name: origin
      branch: master
      force: false
      commit: true
      commit_message: '[skip ci] Update HISTORY.md'
      ssh_key:
        from_secret: CICD_BOT_PRIV_KEY

image_pull_secrets:
  - dockerconfigjson

trigger:
  branch:
    - master
  event:
    - push
```

I have tried to set `remote` as conclusion of https://github.com/appleboy/drone-git-push/issues/43 but it does not seem to work:

If I add the following piece of yaml:

```
remote: git@gitlab.com:<repo>
```

I get the following error:

```
error: remote origin already exists.
exit status 3
```
