### ISSUE TITLE
Woodpecker SSH push 

### ISSUE THREAD

**Issue by MB175** [appleboy/drone-git-push#58]
- Is the key even loaded in the second configuration ? **(Examples below)**
- If the format really is invalid in the first example, what format should the private key be and does it need to be parsed somehow ?

---

**Environment 1:**

Secret has been set *ssh_key*, with rsa or ed key same result.

I also tried to change the line endings of the keys with sed, no luck.

```
sed ':b;N;$!bb;s/\n/\\n/g'
```

.woodpecker.yml

```

pipeline:
  publish:
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:<removed>
      force: false
      commit: true
      commit_message: "Drone build ${DRONE_COMMIT_SHA:0:7}"
      author_name: "John Doe"
      author_email: "johndoe123@example.com"
      ssh_key:
        from_secret: ssh_key


```

```
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
Load key "/root/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Environment 2:**

Same as in Environment 1 just without the definition of the secret name.

.woodpecker.yml

```

pipeline:
...
...
      author_email: "johndoe123@example.com"
      #ssh_key:
      # from_secret: ssh_key


```

```
Host key verification failed.
fatal: Could not read from remote repository.
```

---
