### ISSUE TITLE
[Docs] Commit and push only subdir to another branch (GitHub/CodeBerg Pages)

### ISSUE THREAD

**Issue by vivi90** [appleboy/drone-git-push#94]
I have currently a _workflow_ with an **build** step and a **deploy** step, that works as expected:

```yml
when:
  - event: push
    branch: main

steps:
  build:
    image: node:slim
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm run build

  deploy:
    image: alpine/git
    secrets:
      - git_token
    environment:
      - BUILD_DIR=dist
    commands:
      # Git configuration
      - git config --local user.name "$CI_COMMIT_AUTHOR"
      - git config --local user.email "$CI_COMMIT_AUTHOR_EMAIL"
      - git clone -b pages https://$GIT_TOKEN@codeberg.org/${CI_REPO}.git pages
      # Copy build
      - cp -ar $BUILD_DIR/. pages/
      - cp .domains $CI_REPO_NAME || true # Ignore if it doesn't exist
      # Commit & Push
      - cd pages
      - git add .
      - git commit -m "$CI_COMMIT_MESSAGE"
      - git push
```

How can i achieve the _same_ as:
```yml
...

steps:
  ...

  deploy:
    image: alpine/git
    secrets:
      - git_token
    environment:
      - BUILD_DIR=dist
    commands:
      # Git configuration
      - git config --local user.name "$CI_COMMIT_AUTHOR"
      - git config --local user.email "$CI_COMMIT_AUTHOR_EMAIL"
      - git clone -b pages https://$GIT_TOKEN@codeberg.org/${CI_REPO}.git pages
      # Copy build
      - cp -ar $BUILD_DIR/. pages/
      - cp .domains $CI_REPO_NAME || true # Ignore if it doesn't exist
      # Commit & Push
      - cd pages
      - git add .
      - git commit -m "$CI_COMMIT_MESSAGE"
      - git push
```

but with [appleboy/drone-git-push](https://woodpecker-ci.org/plugins/Git%20Push)?
