### ISSUE TITLE
Custom DNS support

### ISSUE THREAD

**Issue by kSzajo** [appleboy/drone-git-push#97]
Hello,

 I am self hosting both gitea and woodpecker. I encounter following error:

```
fatal: could not read Username for 'https://gitea.example.com': No such device or address
```

step declaration:
```
  - name: push commit
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: master
      local_ref: master
```

Is there option to set custom DNS? I had similar issue when tried to push image using docker buildx plugin. Setting `custom_dns` helped

```
      custom_dns:
        - 10.10.10.1
        - 8.8.8.8
```       
docker buildx reference 
https://woodpecker-ci.org/plugins/Docker%20Buildx
